config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, :except => [:show] do
    collection do
      get '/new' => 'posts#new' # catch new posts before it reaches slug
      get '/:slug' => 'posts#show', :as => :show
      get '/index' => redirect('/posts')
    end
  end

  get 'dashboard' => 'blog#dashboard', :as => :dashboard

  get 'sitemap.xml', to: 'sitemaps#index', defaults: { format: :xml }
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
require "redcarpet/render_strip"

class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id", required: true

  has_many :tags, as: :taggable, dependent: :destroy

  validates :title, :body, presence: true
  before_save :generate_slug, :set_published_at

  scope :published, -> {
    where("published_at < ? and draft is not true", Time.zone.now)
  }

  def plain_body
    without_images = body.to_s.gsub(/\!?\[.+\]\(.+\)/, "").gsub(/\s{2,}/, "")
    without_html = html_sanitizer.sanitize(without_images)
    markdown_render.render(without_html).strip
  end

  def banner
    md = body.to_s.match(/\!\[.+\]\((.+)\)/)
    md && md[1]
  end

  def generate_slug
    if slug.nil? || title_changed?
      time_stamp = published_at || created_at || Time.zone.now
      self.slug = "#{time_stamp.strftime("%m-%d-%Y")}-" \
        "#{CGI.escape(title.downcase.tr(" ", "-"))}"
    end
  end

  def set_published_at
    if !draft && published_at.nil?
      self.published_at = created_at || Time.zone.now
    end
  end

  private

  def html_sanitizer
    @html_sanitizer ||= Rails::Html::FullSanitizer.new
  end

  def markdown_render
    @markdown_render ||= Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :taggable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    dashboard_path
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @unpublished_posts = Post.order("created_at desc").where("published_at > ? or draft", Time.now)
    @new_image = Image.new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i{index show}
  before_action :find_post, except: %i{index new create}

  def index
    @posts = list_of_posts
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
    @post_publish_time = @post.published_at &&
      @post.published_at.strftime("%b %d, %Y")
    render :new
  end

  def create
    @post = current_user.posts.includes(:tags).create(post_params)
    update_tags
    redirect_to dashboard_path
  end

  def update
    @post.update(post_params)
    update_tags
    redirect_to dashboard_path
  end

  def destroy
    @post.try(:destroy)
    redirect_to dashboard_path
  end

  private

  def find_post
    if params[:slug]
      @post = Post.includes(:tags).find_by(slug: CGI.escape(params[:slug]))
    end

    @post ||= Post.includes(:tags).find_by(id: params[:id])
    redirect_to root_path if @post.nil?
  end

  def update_tags
    new_tags = params[:tags].split(",").map { |tag| tag.strip.downcase }
    old_tags = @post.tags.pluck(:name)
    diff = old_tags - new_tags

    @post.tags.where(name: diff).destroy_all

    new_tags.each do |tag|
      @post.tags.find_or_create_by(name: tag)
    end
  end

  def post_params
    params.require(:post).permit!
  end

  def list_of_posts
    posts = Post.includes(:tags).published.order("posts.published_at desc")

    if params[:tags]
      posts = posts.where(tags: { name: params[:tags], taggable_type: "Post" })
    end

    posts.paginate(page: params[:page] || 1, per_page: 5)
  end
end

app/controllers/projects/connect_four_controller.rb
module Projects
  class ConnectFourController < ApplicationController
    def show
      render :show, layout: "projects/connect_four"
    end
  end
end

app/controllers/projects/home_controller.rb
module Projects
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  layout nil

  def index
    headers["Content-Type"] = "application/xml"
    @posts = Post.published
    if stale?(@posts.last)
      respond_to do |format|
        format.xml
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  # skills are arranged font-icon classname => "display name"
  DAILY_SKILLS = [
    [:svgs_java, "Java"],
    [:svgs_ruby, "Ruby"],
    [:svgs_javascript, "Javascript"],
    [:svgs_hbase, "HBase"],
    [:svgs_rails, "Rails"],
    [:svgs_hadoop, "Hadoop"],
    [:svgs_kafka, "Kafka"],
    [:svgs_zookeeper, "Zookeeper"],
    [:svgs_docker, "Docker"],
    [:svgs_kubernetes, "Kubernetes"],
    [:svgs_postgresql, "Postgres"],
    [:svgs_mongodb, "MongoDB"],
    [:svgs_aws, "AWS"],
    [:svgs_memcached, "Memcached"],
    [:svgs_elasticsearch, "ElasticSearch"],
    [:svgs_react, "React"],
    [:svgs_redux, "Redux"],
    [:svgs_jquery, "jQuery"],
    [:svgs_sass, "Sass"],
    [:svgs_css3, "CSS3"],
    [:svgs_heroku, "Heroku"],
    [:svgs_html5, "HTML5"],
    [:svgs_nginx, "nginx"],
    [:svgs_git, "Git"],
    [:svgs_github, "Github"],
    [:svgs_vim, "Vim"],
    [:svgs_linux, "Linux"],
  ]

  SKILL_TYPE = {
    daily: DAILY_SKILLS,
  }

  def list_skills(type)
    SKILL_TYPE[type].map do |(svg_name, skill_name)|
      "<div class=\"pull-left skill-container text-center\">" \
        "#{image_tag("#{parse_image_path(svg_name)}", class: "skill-icon")}" \
        "<br>" \
        "#{skill_name}</div>"
    end.join("").html_safe
  end

  def parse_image_path(image_name)
    File.join(image_name.to_s.split("_"))
  end
end

app/helpers/meta_tag_helper.rb
module MetaTagHelper
  def page_title
    subtitle = if @post
      @post.title.to_s.capitalize
    elsif @title
      @title
    else
      "Software Engineer"
    end

    "Kaoru K - #{subtitle}"
  end

  def page_description
    %{
Software Engineer based in the Bay Area, San Francisco. Helping companies turn
ideas into amazon products. I write about technical and personal learnings as I
advance through my career and life.
    }.squish
  end

  def page_keywords
    keywords = @post&.tags&.map(&:name) || []

    (keywords + %w{
      software
      engineer
      technical
      writing
      java
      ruby
      javascript
    }).join(", ")
  end
end

app/views/blog/dashboard.html.erb
<div class="row center-column home-container">
  <div class="col-xs-6">
    <%= link_to "Write New Post", new_post_path %>&nbsp;&nbsp;&nbsp;
    <%= link_to "Log Out", destroy_user_session_path, :method => :delete%>
  </div>
  <div class="col-xs-6">
    <h4>Unpublished Posts</h4>
    <ul>
      <% @unpublished_posts.each do |post| %>
        <li><%= link_to post.title, edit_post_path(post.id)%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<section class="hero-container home-container">
  <%= render "shared/navigation" %>
</section>

<section class="summary-container home-container text-center inverse-section">
  <h2>4 One One</h2>
  <div class="contant-links">
    <%= render "shared/contact_info" %>
  </div>

  <p class="center--column">
    Software Engineer based in the Bay Area.
  </p>

  <p class="center--column">
    Helping companies turn ideas into amazing products.
  </p>

  <p class="center--column">
    Self-starter, all about the <strong>#hustle</strong>.
  </p>

  <p class="center--column">
    Believes learning is a lifelong event.
  </p>
</section>

<section class="home-container">
  <h2 class="text-center">Work Experience</h2>
  <div class="work-exp-container clearfix">
    <div class="work-col employer-info">
      <h3>Sift Science</h3>
      <h4>Software Engineer</h4>
      <p>
        <a href="https://siftscience.com" target="_blank">siftscience.com</a><br>
        May 2016<br>
        Current
      </p>
    </div>
    <div class="work-col">
      <p>
      Sift Science prevents online fraud using Machine Learning. I was a key
      team member of then the applications team before moving to the
      infrastructure team. Some of my accomplishments are:
      </p>
      <ul>
        <li>
          Redesigned a state system significantly improving stability and
          reducing code complexity.
        </li>
        <li>
          Built a single page application to allow on-call engineers to quickly
          failover to a replica database using React, Redux, ZooKeeper,
          Kubernetes and Docker.
        </li>
        <li>
          Restructured data model saving $25,000 worth of storage costs per
          month.
        </li>
        <li>
          Worked on varies data pipelines fixing race conditions and elusive
          bugs.
        </li>
      </ul>
    </div>
  </div>

  <div class="work-exp-container clearfix">
    <div class="work-col employer-info">
      <h3>Binti</h3>
      <h4>Contract Software Engineer</h4>
      <p>
        <a href="https://binti.com" target="_blank">Binti.com</a><br>
        February 2016<br>
        April 2018
      </p>
    </div>
    <div class="work-col">
      <p>
        Binti helps foster care by simplifying paper work
        allowing foster care workers to concentrate on the children and not
        the logistics. I was the second engineer of now a fifteen person
        company. I've helped:
      </p>
      <ul>
        <li>
          Build three different prototypes from idea to production winning
          multiple government contracts enabling Binti to grow from a two-person
          team to a fifteen person company.
        </li>
        <li>
          Setup the first reporting dashboard allowing managers to view the
          performance of individuals and to distribute work more efficiently.
        </li>
        <li>
          Provided expertise on JavaScript and SASS best practices.
        </li>
      </ul>
    </div>
  </div>

  <div class="work-exp-container clearfix">
    <div class="work-col employer-info">
      <h3>Inside</h3>
      <h4>Software Engineer</h4>
      <p>
        <a href="https://inside.com" target="_blank">Inside.com</a><br>
        April 2015<br>
        February 2016
      </p>
    </div>
    <div class="work-col">
      <p>
        Worked with a remotely based team, to bring important and
        relevant news to users. I've contributed by:
      </p>
      <ul>
        <li>
          Constructing a gulp.js framework allowing us to launch new vertical
          websites to quickly pitch to different companies. Inside won its
          first B2B subscription with a vertical site.
        </li>
        <li>
          Prototyped and launched a Chrome extension doubling the user base.
        </li>
      </ul>
    </div>
  </div>

  <div class="work-exp-container clearfix">
    <div class="work-col employer-info">
      <h3>Spredfast</h3>
      <h4>Software Engineer</h4>
      <p>
        <a href="https://www.spredfast.com" target="_blank">Spredfast.com</a><br>
        December 2013<br>
        April 2015
      </p>
    </div>
    <div class="work-col">
      <p>
        Spredfast helps companies improve their social media presence and
        market at the speed of social. Some achievements include:
      </p>
      <ul>
        <li>
          Building a data pipeline to power in-depth analytic reports
          powered by RedShift providing customers with a 10x ROI.
        </li>
        <li>
          Implemented a strategy to update tables with a CSV file containing
          thousands of rows into MySQL.
        </li>
        <li>
          Worked closely with designers to relaunch the core CMS offering of the
          company.
        </li>
        <li>
          Contributed to admin tooling improving the productivity of internal
          teams.
        </li>
      </ul>
    </div>
  </div>
</section>

<section class="kudos-container home-container text-center inverse-section">
  <h2>Kudos</h2>
  <p>
    "You're one of the best engineers Sift has and I'm not just saying that."
    <br>
    <a href="https://www.linkedin.com/in/leelynne/">Lee Faris</a>
    - Staff Engineer @ Sift Science
  </p>

  <p>
  "I just want to say I really appreciate how aggressively you want to learn new
  stuff and get better. It makes me want to be better too."
  <br>
  <a href="https://www.linkedin.com/in/timbrownatlinkedin">Tim Brown</a>
  - Software Engineer @ Sift Science
  </p>

  <p>
    "Kaoru is one of the big reasons why I love work so much...I feel like he
    does way more than what's asked of him, and he has a drive towards having
    good engineering practices being applied at work."
    <br>
    <a href="https://www.linkedin.com/in/justinhonlee/">Justin Lee</a>
    - Software Engineer @ Sift Science
  </p>

  <p>
  "Hmm. Yeah this is a complicated one to debug. I would see if you can
  [reproduce] with your own user. If you can then ping Kaoru. He likely has his
  hands full, but he knows his s**t"
  <br>
  <a href="https://www.linkedin.com/in/howardr/">Howard Rauscher</a>
  - VP of Engineering @ Spredfast
  </p>
</section>


<section class="home-container">
  <div class="center-column">
    <h2 class="text-center">Technology <i class="fa fa-hand-spock-o"></i></h2>
    <h4>Familiar With</h4>
    <div class="skills-list clearfix">
      <%= list_skills(:daily) %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>

  <meta name="description" content="<%= page_description %>">
  <meta name="keywords" content="<%= page_keywords %>">
  <meta name="viewport" content="width=device-width">
  <meta charset="UTF-8">

  <%= render "shared/social_media_tags" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <meta name="viewport"
        content="width=device-width,
                 initial-scale=1.0,
                 maximum-scale=12.0,
                 minimum-scale=.25,
                 user-scalable=yes"/>

  <%= render "shared/ga_analytics" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <%= render "shared/footer" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascripts %>
</body>
</html>

app/views/layouts/projects/connect_four.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>

  <meta name="viewport" content="width=device-width">
  <meta charset="UTF-8">

  <%= render "shared/social_media_tags" %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="center-container-column">
    <header>

      <h1 class="page-title">
        <a href="/" class="title-link">
          <div>Kaoru</div>
          <div>Kohashigawa</div>
        </a>
      </h1>

      <div class="sub-title text-uppercase">
        Motivation, Code, &amp; Things
      </div>

    </header>
    <%= render "shared/navigation" %>
    <%= yield %>
  </div>

  <%= javascript_include_tag 'projects/connect_four' %>
  <%= yield :javascript %>
</body>
</html>

app/views/posts/_convert_post_markdown.html.erb
<script>
  !function () {
    $('.post-body').each(function (idx, el) {
      var $el = $(el);
      $el.html(window.marked($el.text()));
    });

  } ();
</script>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="center-column">
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, :class => "form-control", :required => true %>
        </div>

        <div class="form-group">
          <%= label_tag :tags %>
          <%= text_field_tag :tags, @post.tags.pluck(:name).join(","), :class => "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label>
            Publish On: <span class="publish-display"></span>
            <input type="text" class="input-publish-on form-control" value="<%= @post_publish_time %>">
            <%= f.hidden_field :published_at %>
          </label>

          <div class="form-group">
            <%= f.radio_button :draft, true %>
            <label for="post_draft_true">Draft</label>&nbsp;&nbsp;
            <%= f.radio_button :draft, false %>
            <label for="post_draft_false">Final</label>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Save", :class => "btn btn-primary" %>
    </div>

    <textarea name="post[body]"
              id="post-body"
              cols="96"
              rows="20"
              class="form-control"
              required><%= @post.body %></textarea>
    <div id="post-preview" class="clearfix post-body"></div>
  </div>
<% end %>


<%= content_for :javascripts do %>
  <script>
    $(function () {
      var $publishDisplay = $('.publish-display');
      var $publishInput = $('.input-publish-on');
      var $publishVal = $('#post_published_at');

      $publishInput.on('keyup', _.throttle(function (e) {
        var rawDate = $publishInput.val();
        var parsed = Date.parse(rawDate);
        if (parsed) {
          $publishVal.val(parsed);
          $publishDisplay.text(parsed.toString('MMM d, yyyy'));
        }
      }, 1000));

      var $preview = $('#post-preview');
      var $postBody = $('#post-body');

      $preview.html(window.marked($postBody.val()));
      $postBody.on('keyup', _.throttle(function (e) {
        $preview.html(window.marked($postBody.val()));
      }, 1000));
    });
  </script>
<% end %>

app/views/posts/_post.html.erb
<article class="post-container center-column">
  <section class="clearfix double-column-container">
    <header class="post-title-container column">
      <h3><%= post.title %></h3>
      <p class="tags-container">
        <span class="post-timestamp">
          <%= (post.published_at || post.updated_at).strftime("%B %-d, %Y") %>
        </span><br>

        <% post.tags.each do |tag| %>
          <%= link_to tag.name, "/posts?tags=#{tag.name}" %>
        <% end %>
      </p>
      <p class="deep-link">
        <% if controller.action_name != "show" %>
          <%= link_to "Link", post_path(post.slug) %>
        <% end %>
      </p>
      <% if current_user %>
        <div class="post-action-container">
          <%= link_to "edit", edit_post_path(post) %> |
          <%= link_to "delete", post_path(post), :method => :delete %>
        </div>
      <% end %>
    </header>

    <p class="post-body clearfix column"><%= post.body %></p>
  </section>
  <% if action_name == "show" %>
    <div id="disqus_thread"></div>
  <% end %>
</article>

app/views/posts/index.html.erb
<div class="center-column">
  <%= render "shared/navigation" %>
</div>

<div class="posts-container">
  <% @posts.each do |post| %>
    <%= render "post", post: post %>
  <% end %>
</div>

<div class="center-column clearfix">
  <div class="pull-right">
    <%= will_paginate @posts,
      :inner_window => 1,
      :next_label => '<i class="fa fa-arrow-circle-right"></i>',
      :previous_label => '<i class="fa fa-arrow-circle-left"></i>' %>
  </div>
</div>

<% content_for :javascripts do %>
  <%= render "convert_post_markdown" %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/navigation" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="center-column">
  <%= render "shared/navigation" %>
</div>
<%= render "post", post: @post %>

<% content_for :javascripts do %>
  <%= render "convert_post_markdown" %>
  <%= render "shared/disqus_comments" %>
<% end %>

app/views/projects/home/index.html.erb
<h2>Personal Projects</h2>

<%= link_to "Connect Four!", projects_connect_four_path %>

app/views/shared/_contact_info.html.erb
<a href="https://twitter.com/devkaoru"
   class="icon-link"
   title="Kaoru's Twitter Account"
   target="_blank"
   rel="external">
  Twitter
</a>
|
<a href="https://www.linkedin.com/in/kaoruk"
   class="icon-link"
   title="Kaoru's LinkedIn Account"
   target="_blank"
   rel="external">
  LinkedIn
</a>
|
<a href="https://www.github.com/kaorudev"
   class="icon-link"
   title="Kaoru's Github Account"
   target="_blank"
   rel="external">
  Github
</a>
<br>
<a href="#" class="email"></a><br>
<%= link_to "Resume (pdf)", asset_path("resume.pdf"), type: :documents %>

app/views/shared/_disqus_comments.html.erb
<% content_for :javascripts do %>
  <script>

  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

  var disqus_config = function () {
    // Replace PAGE_URL with your page's canonical URL variable
    this.page.url = '<%= "https://#{request.host}/#{@post.slug}" %>';
    // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    this.page.identifier = 'post-<%= @post.id %>';
  };

  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://kaoruk.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<% end %>

app/views/shared/_footer.html.erb
<footer class="clearfix inverse-section">
  <div class="pull-left"></div>
  <div class="pull-right text-right">
    <%= render "shared/contact_info" %>
  </div>
</footer>

app/views/shared/_ga_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV["GA_ANALYTICS_ID"] %>', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_navigation.html.erb
<div class="top-nav-container">
  <h1 class="text-uppercase">
    <span>Kaoru</span><br>
    <span class="sub">Kohashigawa</span>
  </h1>
  <nav>
    <%= link_to "home", root_path %> |
    <%= link_to "blog", posts_path %>
    <% if current_user %>
      | <%= link_to "dashboard", dashboard_path %>
    <% end %>
  </nav>
</div>

app/views/shared/_social_media_tags.html.erb
<meta name="description" content="">

<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="<%= page_title %>">
<meta itemprop="description" content="">
<meta itemprop="image" content="">

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="www.kaoruk.com">
<meta name="twitter:title" content="<%= page_title %>">
<meta name="twitter:description" content="<%= @post.try(:plain_body) %>">
<meta name="twitter:creator" content="@devkaoru">
<!-- Twitter summary card with large image must be at least 280x150px -->
<meta name="twitter:image:src" content="<%= @post.try(:banner) %>">

<!-- Open Graph data -->
<meta property="og:title" content="<%= page_title %>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<%= @post.try(:id) ? show_posts_url(@post.slug) : root_url %>" />
<meta property="og:image" content="<%= @post.try(:banner) %>" />
<meta property="og:description" content="<%= @post.try(:plain_body) %>" />
<meta property="og:site_name" content="<%= page_title %>" />
<meta property="article:author" content="devkaoru">
<meta property="article:published_time" content="<%= @post.try(:published_at) %>" />
<meta property="article:modified_time" content="<%= @post.try(:updated_at) %>" />
<meta property="article:section" content="Article Section" />
<meta property="article:tag" content="<%= @post ? @post.tags.pluck(:name) : '' %>" />

app/views/sitemaps/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.kaoruk.com</loc>
    <lastmod><%= ENV["DEPLOY_TIMESTAMP"] %></lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <% @posts.each do |post| %>
    <url>
      <loc>https://www.kaoruk.com/posts/<%= post.slug %></loc>
      <changefreq>monthly</changefreq>
      <priority>0.5</priority>
    </url>
  <% end %>
</urlset>